#ifndef TIMER1 16BIT TYPEDEF_H_
#define TIMER1 16BIT TYPEDEF_H_

typedef enum {
	TIMER1_NORMAL,
	TIMER1_CTC_OCR1A,
	TIMER1_FAST_PWM_ICR1,
	TIMER1_FAST_PWM_OCR1A
} Timer1Mode;

typedef enum {
	TIMER1_NO_CLOCK,
	TIMER1_NO_PRESCALER,
	TIMER1_PRESCALER_8,
	TIMER1_PRESCALER_64,
	TIMER1_PRESCALER_256,
	TIMER1_PRESCALER_1024
} Timer1Prescaler;

typedef enum {
	CHANNEL_A,
	CHANNEL_B
} Timer1Channel;

#endif /* TIMER1 16BIT TYPEDEF_H_ */